###################### Winlogbeat Configuration for ELK Stack (Testing Environment) ########################

# ======================== Winlogbeat specific options =========================

winlogbeat.event_logs:
  - name: Application
    ignore_older: 72h
    # Added a field to allow separate indexing/searching
    fields:
      index: "win_application"
    tags: ["application", "log"]
  
  - name: System
    # Added a field for indexing purposes
    fields:
      index: "win_system"
    tags: ["system", "status"]
  
  - name: Security
    # Updated event_id list to include additional critical IDs for better threat detection:
    #  • 4624, 4625, 4634, 4672: Logon/logoff and privilege use
    #  • 4688, 4697: Process creation and service installation
    #  • 4720, 4722, 4723, 4724, 4725, 4726, 4732, 4740: User account management
    #  • 4768, 4776: Kerberos events
    #  • 5140, 5145: Network file share events
    #  • 4728, 4735, 4756: Group membership changes
    #  • 1102: Security log cleared
    event_id: 4624,4625,4634,4672,4688,4697,4720,4722,4723,4724,4725,4726,4732,4740,4768,4776,5140,5145,4728,4735,4756,1102
    fields:
      index: "win_security"
    tags: ["security", "authentication", "access"]
  
  - name: Microsoft-Windows-Sysmon/Operational
    # Updated event_id list to include a broader range of Sysmon events while excluding event id 4.
    # This will capture detailed process, network, and file-related events.
    event_id: 1,3,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23
    # Exclude event id 4 (Sysmon service state change) as it's generally less useful.
    exclude_event_ids: 4
    fields:
      index: "win_sysmon"
    tags: ["sysmon", "process", "network", "file"]
  
  - name: Windows PowerShell
    event_id: 400,403,600,800
    fields:
      index: "win_powershell"
    tags: ["powershell", "scripting", "execution"]
  
  - name: Microsoft-Windows-PowerShell/Operational
    event_id: 4103,4104,4105,4106
    fields:
      index: "win_powershell_operational"
    tags: ["powershell", "operational", "scriptblock"]
  
  - name: ForwardedEvents
    fields:
      index: "win_forwarded"
    tags: ["forwarded"]

# ====================== Elasticsearch template settings =======================

setup.template.settings:
  index.number_of_shards: 1
  # Uncomment the following if you want best compression
  # index.codec: best_compression

# ================================== General ===================================

# Uncomment to set a custom name for this Winlogbeat instance:
name: "winlogbeat-testing"
tags: ["testing", "windows-monitoring"]
fields:
  environment: testing

# ================================= Dashboards =================================

setup.dashboards.enabled: true

# =================================== Kibana ===================================

setup.kibana:
  host: "192.168.10.33:5601"        #Change the ip address as per you Configuration

# ================================== Outputs ===================================

# ---------------------------- Logstash Output -------------------------------
output.logstash:
  hosts: ["192.168.10.33:5044"]         #Change the ip address as per you Configuration

# ---------------------------- Console Output (For Testing) -------------------
# Uncomment to see output directly in console during testing
output.console:
  enabled: false  # Change to true when needed for direct console output
  pretty: true    # Format JSON for readability

# ================================= Processors =================================

processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~
  - add_process_metadata:
      match_pids: [process.pid]
  - add_locale: ~
  # Uncomment for sampling during high-volume testing
  # - drop_event:
  #     when:
  #       probability: 0.8  # Keep 80% of events

# ================================== Logging ===================================

# For testing: enhanced logging to help troubleshoot issues
logging.level: debug  # Changed from info to debug for more verbosity
logging.selectors: ["*"]  # Log everything during testing
logging.metrics.enabled: true  # Add metrics logging
logging.metrics.period: 30s    # Report metrics every 30 seconds

logging.to_files: true
logging.files:
  path: "C:/Program Files/Winlogbeat/logs"
  name: winlogbeat
  keepfiles: 7
  permissions: 0644

# Enable file rotation
logging.files.rotateeverybytes: 10485760  # Rotate after 10MB

# ============================= Monitoring Configuration ==============================

# Enable internal monitoring to report Winlogbeat metrics to Elasticsearch
monitoring:
  enabled: true
  elasticsearch:
    hosts: ["192.168.10.33:9200"]       #Change the ip address as per you Configuration

# ============================== Memory and Performance Settings ======================

# Adjust queue settings for testing efficiency
queue.mem:
  events: 4096
  flush.min_events: 256  # Flush more frequently during testing
  flush.timeout: 2s      # Reduced flush timeout for testing

# ============================== End of Configuration ===============================